AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  swiftnewsletterservice

  Sample SAM Template for swiftnewsletterservice

Globals:
  Function:
    Timeout: 10

Resources:
  ScheduledEmailExtractorFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess

  ScheduledEmailExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: scheduled_email_extractor/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Role: !GetAtt ScheduledEmailExtractorFunctionRole.Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(05 0 ? * MON *)

Outputs:
  ScheduledEmailExtractorFunction:
    Description: "Scheduled Email Extractor Function Lambda Function ARN"
    Value: !GetAtt ScheduledEmailExtractorFunction.Arn
  ScheduledEmailExtractorFunctionIamRole:
    Description: "Scheduled Email Extractor Function IAM Role ARN"
    Value: !GetAtt ScheduledEmailExtractorFunctionRole.Arn
